root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/api/*.go"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev APP_PORT=8080 ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  log = "air-build.log"

[log]
  time = true

[misc]
  clean_on_exit = true
